### ISSUE TITLE
Terminal visibility

### ISSUE THREAD

**Issue by saubiswa** [zedsec390/tn3270lib#2]
How can I make the terminal visible?

**Comment by mainframed** [comment]
set the debug up higher. See the section labeled 'Debugging' in the readme. 

If you mean by calling a function use:

```
>>> data = tn3270.get_screen()
>>> print data
```

As outlined in the readme

**Comment by saubiswa** [comment]
I meant to say, how can I make the mainframe terminal visible, while operations are performed on that terminal by the tn3270lib program.

**Comment by mainframed** [comment]
Could you please elaborate?
