### ISSUE TITLE
Send Tab character

### ISSUE THREAD

**Issue by nfrankish** [zedsec390/tn3270lib#3]
Howdy,
Im having some issues with the login part.
>>> tn3270.send_cursor("margo")
>>> tn3270.get_all_data()
>>> tn3270.send_cursor("secret")
>>> tn3270.get_all_data()

When i attempt this, this ineviatbely ends with secret being on the screen, but username having disappeared...

               Your USERID     ===>

               Your PASSWORD   ===> Secret

               New PASSWORD    ===>
               Verify PASSWORD ===>
GSSN100E USERID required and has not been supplied.

Is there a better way to tab etween fields? eg send cursor, send tab, send cursor?

**Comment by mainframed** [comment]
To send more than one item, at the moment no. I've implemented this in NSELIB tn3270.lua for nmap but not this python script as yet. 

However, i just pushed a fix that should allow you to log on to TSO now.

**Comment by bhavinkotak** [comment]
Sorry for writing on a closed issue - but can you please suggest/show how to use tab as it seems in my case - it is entering UserID and without going onto next field it is writing down password - hence the authentication is failing

tn3270.send_cursor("UserID")
tn3270.get_all_data()
data = tn3270.get_screen()
print data
tn3270.send_cursor("password")
tn3270.get_all_data()

also I am using Pycharm with python 2.7 - and not able to see what gets posted on the screen, Any specific setting or suggestion? I tried the debug options, but it gives details that is difficult to interpret.
